name: blinkid_flutter
description: Flutter plugin for BlinkID, SDK for scanning and OCR of various identity documents.
version: 7.6.0
homepage: https://microblink.com

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  plugin:
    platforms:
      android:
        package: com.microblink.blinkid.flutter
        pluginClass: BlinkidFlutterPlugin
      ios:
        pluginClass: BlinkidFlutterPlugin
